name: Get full info
on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents:  write

    steps:
      - name: Checkout repository to get info from
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # pin@v6.0.1

      - name: Checkout metadata-validation-scripts
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # pin@v6.0.1
        with:
          repository: symbioticfi/metadata-validation-scripts
          path: metadata-validation-scripts

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # pin@v6.2.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install tsx @actions/core @actions/github

      - name: Generate
        run: npx tsx metadata-validation-scripts/.github/workflows/scripts/extract-metadata.ts

      - name: Release latest full info
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # pin@v2.5.0
        with:
          name: latest
          tag_name: latest
          files: full-info.json
          fail_on_unmatched_files: true

      # Sleep to be sure release is updated in GH CDN before triggering a webhook
      - name: Sleep for 30 seconds
        run: sleep 30s
