name: Get full info
on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents:  write

    steps:
      - name: Checkout repository to get info from
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # pin@v6.0.0

      - name: Checkout metadata-validation-scripts
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # pin@v6.0.0
        with:
          repository: symbioticfi/metadata-validation-scripts
          path: metadata-validation-scripts

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # pin@v4.4.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install tsx @actions/core @actions/github

      - name: Generate
        run: npx tsx metadata-validation-scripts/.github/workflows/scripts/extract-metadata.ts

      - name: Release latest full info
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8  # pin@v2.3.2
        with:
          name: latest
          tag_name: latest
          files: full-info.json
          fail_on_unmatched_files: true

      # Sleep to be sure release is updated in GH CDN before triggering a webhook
      - name: Sleep for 30 seconds
        run: sleep 30s
